import {
  SECTIONS_FOLLOWERS_USERS_REQUEST,
  SECTIONS_FOLLOWERS_USERS_SUCCESS,
  SECTIONS_FOLLOWING_LISTS_REQUEST,
  SECTIONS_FOLLOWING_LISTS_SUCCESS,
  SECTIONS_FOLLOWING_USERS_REQUEST,
  SECTIONS_FOLLOWING_USERS_SUCCESS,
  SECTIONS_MOST_FOLLOWED_USERS_REQUEST,
  SECTIONS_MOST_FOLLOWED_USERS_SUCCESS,
  SECTIONS_MOST_POPULAR_LISTS_LOAD_REQUEST,
  SECTIONS_MOST_POPULAR_LISTS_LOAD_SUCCESS,
  SECTIONS_MOST_USED_TAGS_REQUEST,
  SECTIONS_MOST_USED_TAGS_SUCCESS,
  SECTIONS_MY_LISTS_REQUEST,
  SECTIONS_MY_LISTS_SUCCESS,
  SECTIONS_MY_RECENT_BOOKMARKS_REQUEST,
  SECTIONS_MY_RECENT_BOOKMARKS_SUCCESS,
  SECTIONS_MY_TAGS_REQUEST,
  SECTIONS_MY_TAGS_SUCCESS,
  SECTIONS_NEW_LISTS_REQUEST,
  SECTIONS_NEW_LISTS_SUCCESS,
  SECTIONS_NEW_USERS_REQUEST,
  SECTIONS_NEW_USERS_SUCCESS,
  SECTIONS_SIMILAR_LISTS_REQUEST,
  SECTIONS_SIMILAR_LISTS_SUCCESS,
  SECTIONS_TAGS_IN_THIS_LIST_REQUEST,
  SECTIONS_TAGS_IN_THIS_LIST_SUCCESS,
  SECTIONS_USER_LISTS_REQUEST,
  SECTIONS_USER_LISTS_SUCCESS,
  SECTIONS_USER_MOST_USED_TAGS_REQUEST,
  SECTIONS_USER_MOST_USED_TAGS_SUCCESS,
  SECTIONS_USERS_IN_THIS_LIST_REQUEST,
  SECTIONS_USERS_IN_THIS_LIST_SUCCESS,
  SectionsActions,
  SectionsState,
} from './sections.types';

export const initialState: SectionsState = {
  PopularLists: {
    currentIds: [],
    loading: false,
  },
  NewLists: {
    currentIds: [],
    loading: false,
  },
  MostFollowedUsers: {
    currentIds: [],
    loading: false,
  },
};

export const Sections = (state = initialState, action: SectionsActions): SectionsState => {
  switch (action.type) {
    case SECTIONS_MOST_POPULAR_LISTS_LOAD_REQUEST:
    case SECTIONS_MOST_POPULAR_LISTS_LOAD_SUCCESS:
    case SECTIONS_NEW_LISTS_REQUEST:
    case SECTIONS_NEW_LISTS_SUCCESS:
    case SECTIONS_MOST_FOLLOWED_USERS_REQUEST:
    case SECTIONS_MOST_FOLLOWED_USERS_SUCCESS:
    case SECTIONS_NEW_USERS_REQUEST:
    case SECTIONS_NEW_USERS_SUCCESS:
    case SECTIONS_MY_LISTS_REQUEST:
    case SECTIONS_MY_LISTS_SUCCESS:
    case SECTIONS_FOLLOWING_LISTS_REQUEST:
    case SECTIONS_FOLLOWING_LISTS_SUCCESS:
    case SECTIONS_MY_TAGS_REQUEST:
    case SECTIONS_MY_TAGS_SUCCESS:
    case SECTIONS_FOLLOWING_USERS_REQUEST:
    case SECTIONS_FOLLOWING_USERS_SUCCESS:
    case SECTIONS_MOST_USED_TAGS_REQUEST:
    case SECTIONS_MOST_USED_TAGS_SUCCESS:
    case SECTIONS_USER_LISTS_REQUEST:
    case SECTIONS_USER_LISTS_SUCCESS:
    case SECTIONS_FOLLOWERS_USERS_REQUEST:
    case SECTIONS_FOLLOWERS_USERS_SUCCESS:
    case SECTIONS_SIMILAR_LISTS_REQUEST:
    case SECTIONS_SIMILAR_LISTS_SUCCESS:
    case SECTIONS_USERS_IN_THIS_LIST_REQUEST:
    case SECTIONS_USERS_IN_THIS_LIST_SUCCESS:
    case SECTIONS_TAGS_IN_THIS_LIST_REQUEST:
    case SECTIONS_TAGS_IN_THIS_LIST_SUCCESS:
    case SECTIONS_MY_RECENT_BOOKMARKS_REQUEST:
    case SECTIONS_MY_RECENT_BOOKMARKS_SUCCESS:
    case SECTIONS_USER_MOST_USED_TAGS_REQUEST:
    case SECTIONS_USER_MOST_USED_TAGS_SUCCESS:
      return Object.assign({}, state, action.payload);

    default:
      return Object.assign({}, state);
  }
};
