export const bookmarks = [
  {
    id: 1,
    title: 'My first bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/123/300/200',
    tags: [
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
      { id: 1, name: 'Cool' },
      { id: 4, name: 'Long text' },
      { id: 6, name: 'Yeah' },
      { id: 5, name: 'Media' },
      { id: 7, name: 'Articles' },
    ],
    vote: undefined,
  },
  {
    id: 2,
    title: 'A second bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/21/300/200',
    tags: [
      { id: 4, name: 'Long text' },
      { id: 3, name: 'News' },
      { id: 1, name: 'Cool' },
      { id: 2, name: 'Media' },
      { id: 5, name: 'Media' },
      { id: 6, name: 'Yeah' },
      { id: 7, name: 'Articles' },
    ],
    vote: true,
  },
  {
    id: 3,
    title: 'A third bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/42/300/200',
    tags: [
      { id: 5, name: 'Media' },
      { id: 3, name: 'News' },
    ],
    vote: false,
  },
  {
    id: 4,
    title: 'My first bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/56/300/200',
    tags: [
      { id: 7, name: 'Articles' },
      { id: 6, name: 'Yeah' },
      { id: 1, name: 'Cool' },
    ],
    vote: false,
  },
  {
    id: 5,
    title: 'A second bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/32/300/200',
    tags: [
      { id: 7, name: 'Articles' },
      { id: 1, name: 'Cool' },
      { id: 6, name: 'Yeah' },
      { id: 4, name: 'Long text' },
      { id: 2, name: 'Media' },
      { id: 5, name: 'Media' },
      { id: 3, name: 'News' },
    ],
    vote: true,
  },
  {
    id: 6,
    title: 'A third bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/51/300/200',
    tags: [
      { id: 1, name: 'Cool' },
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
      { id: 4, name: 'Cool' },
      { id: 5, name: 'Media' },
      { id: 6, name: 'News' },
    ],
    vote: undefined,
  },
  {
    id: 7,
    title: 'My first bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/46/300/200',
    tags: [
      { id: 1, name: 'Cool' },
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
      { id: 4, name: 'Cool' },
      { id: 5, name: 'Media' },
      { id: 6, name: 'News' },
    ],
    vote: true,
  },
  {
    id: 8,
    title: 'A second bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/6/300/200',
    tags: [
      { id: 1, name: 'Cool' },
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
      { id: 4, name: 'Long text' },
      { id: 5, name: 'Media' },
      { id: 6, name: 'Yeah' },
      { id: 7, name: 'Articles' },
    ],
    vote: undefined,
  },
  {
    id: 9,
    title: 'A third bookmark',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/id/65/300/200',
    tags: [
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
      { id: 1, name: 'Cool' },
      { id: 4, name: 'Long text' },
      { id: 6, name: 'Yeah' },
      { id: 5, name: 'Media' },
      { id: 7, name: 'Articles' },
    ],
    vote: false,
  },
];
