export const links = [
  {
    id: 1,
    title: 'My first link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 1, name: 'Cool' },
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
    ],
    vote: undefined,
  },
  {
    id: 2,
    title: 'A second link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 4, name: 'Photos' },
      { id: 5, name: 'Foo' },
      { id: 6, name: 'Bar' },
    ],
    vote: true,
  },
  {
    id: 3,
    title: 'A third link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 7, name: 'Baz' },
      { id: 8, name: 'Articles' },
      { id: 9, name: 'Danger' },
    ],
    vote: false,
  },
  {
    id: 4,
    title: 'My first link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 1, name: 'Cool' },
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
    ],
    vote: false,
  },
  {
    id: 5,
    title: 'A second link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 4, name: 'Photos' },
      { id: 5, name: 'Foo' },
      { id: 6, name: 'Bar' },
    ],
    vote: true,
  },
  {
    id: 6,
    title: 'A third link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 7, name: 'Baz' },
      { id: 8, name: 'Articles' },
      { id: 9, name: 'Danger' },
    ],
    vote: undefined,
  },
  {
    id: 7,
    title: 'My first link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 1, name: 'Cool' },
      { id: 2, name: 'Media' },
      { id: 3, name: 'News' },
    ],
    vote: true,
  },
  {
    id: 8,
    title: 'A second link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 4, name: 'Photos' },
      { id: 5, name: 'Foo' },
      { id: 6, name: 'Bar' },
    ],
    vote: undefined,
  },
  {
    id: 9,
    title: 'A third link',
    url: 'http://example.com/path',
    img: 'https://picsum.photos/300/200',
    tags: [
      { id: 7, name: 'Baz' },
      { id: 8, name: 'Articles' },
      { id: 9, name: 'Danger' },
    ],
    vote: false,
  },
];
