export const Props = {
  id: 'PopularLists',
  title: 'Popular lists',
  items: [
    {
      id: 0,
      name: 'First list',
      isPrivate: true,
      description: '',
      userId: '',
      image: '',
      bookmarksIds: [],
      membersIds: [],
      tags: [],
      createdAt: '',
      updatedAt: '',
    },
    {
      id: 0,
      name: 'Second list',
      isPrivate: true,
      description: '',
      userId: '',
      image: '',
      bookmarksIds: [],
      membersIds: [],
      tags: [],
      createdAt: '',
      updatedAt: '',
    },
    {
      id: 0,
      name: 'Third list',
      isPrivate: true,
      description: '',
      userId: '',
      image: '',
      bookmarksIds: [],
      membersIds: [],
      tags: [],
      createdAt: '',
      updatedAt: '',
    },
    {
      id: 0,
      name: 'Fourth list',
      isPrivate: true,
      description: '',
      userId: '',
      image: '',
      bookmarksIds: [],
      membersIds: [],
      tags: [],
      createdAt: '',
      updatedAt: '',
    },
    {
      id: 0,
      name: 'Fifth list',
      isPrivate: true,
      description: '',
      userId: '',
      image: '',
      bookmarksIds: [],
      membersIds: [],
      tags: [],
      createdAt: '',
      updatedAt: '',
    },
  ],
};
