import {
  BOOKMARK_CREATE_FAILURE,
  BOOKMARK_CREATE_REQUEST,
  BOOKMARK_CREATE_SUCCESS,
  BOOKMARK_DELETE_FAILURE,
  BOOKMARK_DELETE_SUCCESS,
  BOOKMARK_LOAD_BY_ID_FAILURE,
  BOOKMARK_LOAD_BY_ID_REQUEST,
  BOOKMARK_LOAD_BY_ID_SUCCESS,
  BOOKMARK_UPDATE_FAILURE,
  BOOKMARK_UPDATE_REQUEST,
  BOOKMARK_UPDATE_SUCCESS,
  BOOKMARK_UPDATE_VOTE_REQUEST,
  BOOKMARK_UPDATE_VOTE_SUCCESS,
  BOOKMARKS_LOAD_BY_IDS_FAILURE,
  BOOKMARKS_LOAD_BY_IDS_REQUEST,
  BOOKMARKS_LOAD_BY_IDS_SUCCESS,
  BOOKMARKS_LOAD_REQUEST,
  BOOKMARKS_LOAD_SUCCESS,
  BOOKMARKS_RECOMMENDED_FAILURE,
  BOOKMARKS_RECOMMENDED_REQUEST,
  BOOKMARKS_RECOMMENDED_SUCCESS,
  BookmarksActions,
  BookmarksState,
} from './bookmarks.types';

const initialState: BookmarksState = {
  byKey: {},
  errors: [],
};

export const Bookmarks = (state = initialState, action: BookmarksActions): BookmarksState => {
  switch (action.type) {
    case BOOKMARKS_LOAD_REQUEST:
    case BOOKMARKS_LOAD_SUCCESS:
    case BOOKMARK_UPDATE_VOTE_REQUEST:
    case BOOKMARK_UPDATE_VOTE_SUCCESS:
    case BOOKMARK_CREATE_REQUEST:
    case BOOKMARK_CREATE_SUCCESS:
    case BOOKMARK_CREATE_FAILURE:
    case BOOKMARK_UPDATE_REQUEST:
    case BOOKMARK_UPDATE_SUCCESS:
    case BOOKMARK_UPDATE_FAILURE:
    case BOOKMARK_DELETE_SUCCESS:
    case BOOKMARK_DELETE_FAILURE:
    case BOOKMARKS_RECOMMENDED_REQUEST:
    case BOOKMARKS_RECOMMENDED_SUCCESS:
    case BOOKMARKS_RECOMMENDED_FAILURE:
    case BOOKMARK_LOAD_BY_ID_REQUEST:
    case BOOKMARK_LOAD_BY_ID_SUCCESS:
    case BOOKMARK_LOAD_BY_ID_FAILURE:
    case BOOKMARKS_LOAD_BY_IDS_REQUEST:
    case BOOKMARKS_LOAD_BY_IDS_SUCCESS:
    case BOOKMARKS_LOAD_BY_IDS_FAILURE:
      return Object.assign({}, state, action.payload);
    default:
      return Object.assign({}, state);
  }
};
