import {
  LIST_BOOKMARK_CREATE_FAILURE,
  LIST_BOOKMARK_CREATE_REQUEST,
  LIST_BOOKMARK_CREATE_SUCCESS,
  LIST_BOOKMARK_DELETE_FAILURE,
  LIST_BOOKMARK_DELETE_REQUEST,
  LIST_BOOKMARK_DELETE_SUCCESS,
  LIST_CREATE_FAILURE,
  LIST_CREATE_REQUEST,
  LIST_CREATE_RESET,
  LIST_CREATE_SUCCESS,
  LIST_DELETE_FAILURE,
  LIST_DELETE_REQUEST,
  LIST_DELETE_SUCCESS,
  LIST_UNFOLLOW_FAILURE,
  LIST_UNFOLLOW_REQUEST,
  LIST_UNFOLLOW_SUCCESS,
  LIST_UPDATE_FAILURE,
  LIST_UPDATE_REQUEST,
  LIST_UPDATE_SUCCESS,
  LIST_USER_DELETE_FAILURE,
  LIST_USER_DELETE_REQUEST,
  LIST_USER_DELETE_SUCCESS,
  LIST_USER_UPSERT_FAILURE,
  LIST_USER_UPSERT_REQUEST,
  LIST_USER_UPSERT_SUCCESS,
  LISTS_LOAD_REQUEST,
  LISTS_LOAD_SUCCESS,
  ListsActions,
  ListsState,
} from './lists.types';

const initialState: ListsState = {
  byKey: {},
  currentIds: [],
};

export const Lists = (state = initialState, action: ListsActions): ListsState => {
  switch (action.type) {
    case LISTS_LOAD_REQUEST:
    case LISTS_LOAD_SUCCESS:
    case LIST_CREATE_REQUEST:
    case LIST_CREATE_SUCCESS:
    case LIST_CREATE_FAILURE:
    case LIST_UPDATE_REQUEST:
    case LIST_UPDATE_SUCCESS:
    case LIST_UPDATE_FAILURE:
    case LIST_CREATE_RESET:
    case LIST_UNFOLLOW_REQUEST:
    case LIST_UNFOLLOW_SUCCESS:
    case LIST_UNFOLLOW_FAILURE:
    case LIST_BOOKMARK_CREATE_REQUEST:
    case LIST_BOOKMARK_CREATE_SUCCESS:
    case LIST_BOOKMARK_CREATE_FAILURE:
    case LIST_BOOKMARK_DELETE_REQUEST:
    case LIST_BOOKMARK_DELETE_SUCCESS:
    case LIST_BOOKMARK_DELETE_FAILURE:
    case LIST_DELETE_REQUEST:
    case LIST_DELETE_SUCCESS:
    case LIST_DELETE_FAILURE:
    case LIST_USER_UPSERT_REQUEST:
    case LIST_USER_UPSERT_SUCCESS:
    case LIST_USER_UPSERT_FAILURE:
    case LIST_USER_DELETE_REQUEST:
    case LIST_USER_DELETE_SUCCESS:
    case LIST_USER_DELETE_FAILURE:
      return Object.assign({}, state, action.payload);

    default:
      return Object.assign({}, state);
  }
};
