const constants = {
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  LOG_FAILED: 'LOG_FAILED',
  FIRST_LOAD: 'FIRST_LOAD',
  LOAD_LANGUAGE_STARTED: 'LOAD_LANGUAGE_STARTED',
  LOAD_LANGUAGE_SUCCESS: 'LOAD_LANGUAGE_SUCCESS',
  LOAD_LANGUAGES_STARTED: 'LOAD_LANGUAGES_STARTED',
  LOAD_LANGUAGES_SUCCESS: 'LOAD_LANGUAGES_SUCCESS',
  LOAD_HOMEPAGE_STARTED: 'LOAD_HOMEPAGE_STARTED',
  LOAD_HOMEPAGE_SUCCESS: 'LOAD_HOMEPAGE_SUCCESS',
  NAVIGATED_ROUTE_START: 'NAVIGATED_ROUTE_START',
  NAVIGATED_ROUTE_STARTED: 'NAVIGATED_ROUTE_STARTED',
  NAVIGATED_ROUTE_FINISHED: 'NAVIGATED_ROUTE_FINISHED',
};

export default constants;
