const constants = {
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  LOG_FAILED: 'LOG_FAILED',
  FIRST_LOAD: 'FIRST_LOAD',
  LOAD_LANGUAGE_STARTED: 'LOAD_LANGUAGE_STARTED',
  LOAD_LANGUAGE_SUCCESS: 'LOAD_LANGUAGE_SUCCESS',
  LOAD_LANGUAGES_STARTED: 'LOAD_LANGUAGES_STARTED',
  LOAD_LANGUAGES_SUCCESS: 'LOAD_LANGUAGES_SUCCESS',
  LOAD_MOCK_DATA_ONE_STARTED: 'LOAD_MOCK_DATA_ONE_STARTED',
  LOAD_MOCK_DATA_ONE_SUCCESS: 'LOAD_MOCK_DATA_ONE_SUCCESS',
  LOAD_MOCK_DATA_TWO_STARTED: 'LOAD_MOCK_DATA_TWO_STARTED',
  LOAD_MOCK_DATA_TWO_SUCCESS: 'LOAD_MOCK_DATA_TWO_SUCCESS',
};

export default constants;
