const constants = {
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  LOG_FAILED: 'LOG_FAILED',
  FIRST_LOAD: 'FIRST_LOAD',
  LOAD_LANGUAGE_STARTED: 'LOAD_LANGUAGE_STARTED',
  LOAD_LANGUAGE_SUCCESS: 'LOAD_LANGUAGE_SUCCESS',
  LOAD_LANGUAGES_STARTED: 'LOAD_LANGUAGES_STARTED',
  LOAD_LANGUAGES_SUCCESS: 'LOAD_LANGUAGES_SUCCESS',
  LOAD_HOMEPAGE_STARTED: 'LOAD_HOMEPAGE_STARTED',
  LOAD_HOMEPAGE_SUCCESS: 'LOAD_HOMEPAGE_SUCCESS',
  LOAD_WHOPAGE_STARTED: 'LOAD_WHOPAGE_STARTED',
  LOAD_WHOPAGE_SUCCESS: 'LOAD_WHOPAGE_SUCCESS',
};

export default constants;
