import {
  SESSION_FORGOT_PASSWORD_FAILURE,
  SESSION_FORGOT_PASSWORD_REQUEST,
  SESSION_FORGOT_PASSWORD_SUCCESS,
  SESSION_LOG_IN_FAILURE,
  SESSION_LOG_IN_REQUEST,
  SESSION_LOG_IN_SUCCESS,
  SESSION_LOG_OUT_FAILURE,
  SESSION_LOG_OUT_REQUEST,
  SESSION_LOG_OUT_SUCCESS,
  SESSION_RESET_ERRORS,
  SESSION_RESET_PASSWORD_FAILURE,
  SESSION_RESET_PASSWORD_REQUEST,
  SESSION_RESET_PASSWORD_SUCCESS,
  SESSION_SIGN_UP_FAILURE,
  SESSION_SIGN_UP_REQUEST,
  SESSION_SIGN_UP_SUCCESS,
  SESSION_UPDATE_DETAILS_FAILURE,
  SESSION_UPDATE_DETAILS_REQUEST,
  SESSION_UPDATE_DETAILS_SUCCESS,
  SessionActions,
  SessionState,
} from './session.types';

const initialState: SessionState = {
  errors: [],
};

export const Session = (state = initialState, action: SessionActions): SessionState => {
  switch (action.type) {
    case SESSION_LOG_IN_REQUEST:
    case SESSION_LOG_IN_SUCCESS:
    case SESSION_LOG_IN_FAILURE:
    case SESSION_LOG_OUT_REQUEST:
    case SESSION_LOG_OUT_SUCCESS:
    case SESSION_LOG_OUT_FAILURE:
    case SESSION_SIGN_UP_REQUEST:
    case SESSION_SIGN_UP_SUCCESS:
    case SESSION_SIGN_UP_FAILURE:
    case SESSION_FORGOT_PASSWORD_REQUEST:
    case SESSION_FORGOT_PASSWORD_SUCCESS:
    case SESSION_FORGOT_PASSWORD_FAILURE:
    case SESSION_RESET_PASSWORD_REQUEST:
    case SESSION_RESET_PASSWORD_SUCCESS:
    case SESSION_RESET_PASSWORD_FAILURE:
    case SESSION_UPDATE_DETAILS_REQUEST:
    case SESSION_UPDATE_DETAILS_SUCCESS:
    case SESSION_UPDATE_DETAILS_FAILURE:
    case SESSION_RESET_ERRORS:
      return Object.assign({}, state, action.payload);

    default:
      return Object.assign({}, initialState, state);
  }
};
